Repository Sinclebear/makehabit_BE, pull requests merged in 2022-03, with the labels that each got.

#44 API 수정 및 jest 테스트코드 수정
  server/controller/challenge.js
  server/jest/challenge.spec.js
  server/models/challenge.js
  server/modules/calcProperty.js
Labels: enhancement

#51 🐛 챌린지 조회에서 경과날짜가 소수점으로 나오는 현상 수정
  server/modules/calcProperty.js
Labels: bug

#56 Ranking API 추가
  server/controller/proofshot.js
  server/controller/user.js
  server/jest/proofshot.spec.js
  server/models/user.js
  server/routes/user.js
Labels: enhancement

#63 Swagger에 Nginx 서버 주소 추가
  server/modules/swagger.js
Labels: bug, enhancement

#60 챌린지 정책 관련 수정 (당일 참여 가능, 하루 작성 가능한 게시글 수 제한)
  server/controller/challenge.js
  server/models/challenge.js
  server/modules/calcProperty.js
Labels: enhancement
